// lib/airports.js
// Aeropuertos usados por AirportPicker. Lista completa agrupada por país/región.

export const AIRPORTS = [
  // España
  { iata: 'MAD', name: 'Madrid Barajas',           region: '🇪🇸 España' },
  { iata: 'BCN', name: 'Barcelona El Prat',         region: '🇪🇸 España' },
  { iata: 'VLC', name: 'Valencia',                  region: '🇪🇸 España' },
  { iata: 'AGP', name: 'Málaga Costa del Sol',      region: '🇪🇸 España' },
  { iata: 'PMI', name: 'Palma de Mallorca',         region: '🇪🇸 España' },
  { iata: 'SVQ', name: 'Sevilla',                   region: '🇪🇸 España' },
  { iata: 'BIO', name: 'Bilbao',                    region: '🇪🇸 España' },
  { iata: 'LPA', name: 'Las Palmas (Gran Canaria)', region: '🇪🇸 España' },
  { iata: 'TFN', name: 'Tenerife Norte',            region: '🇪🇸 España' },
  { iata: 'TFS', name: 'Tenerife Sur',              region: '🇪🇸 España' },
  { iata: 'ALC', name: 'Alicante',                  region: '🇪🇸 España' },
  { iata: 'IBZ', name: 'Ibiza',                     region: '🇪🇸 España' },
  { iata: 'SDR', name: 'Santander',                 region: '🇪🇸 España' },
  { iata: 'VGO', name: 'Vigo',                      region: '🇪🇸 España' },
  { iata: 'OVD', name: 'Asturias',                  region: '🇪🇸 España' },
  { iata: 'ACE', name: 'Lanzarote',                 region: '🇪🇸 España' },
  { iata: 'FUE', name: 'Fuerteventura',             region: '🇪🇸 España' },
  { iata: 'GRX', name: 'Granada',                   region: '🇪🇸 España' },
  { iata: 'MAH', name: 'Menorca',                   region: '🇪🇸 España' },
  { iata: 'REU', name: 'Reus',                      region: '🇪🇸 España' },
  { iata: 'ZAZ', name: 'Zaragoza',                  region: '🇪🇸 España' },
  { iata: 'SCQ', name: 'Santiago de Compostela',    region: '🇪🇸 España' },
  { iata: 'XRY', name: 'Jerez de la Frontera',      region: '🇪🇸 España' },
  { iata: 'LEI', name: 'Almería',                   region: '🇪🇸 España' },
  { iata: 'MJV', name: 'Murcia',                    region: '🇪🇸 España' },
  { iata: 'EAS', name: 'San Sebastián',             region: '🇪🇸 España' },
  // Reino Unido e Irlanda
  { iata: 'LHR', name: 'Londres Heathrow',          region: '🇬🇧 Reino Unido' },
  { iata: 'LGW', name: 'Londres Gatwick',           region: '🇬🇧 Reino Unido' },
  { iata: 'STN', name: 'Londres Stansted',          region: '🇬🇧 Reino Unido' },
  { iata: 'LTN', name: 'Londres Luton',             region: '🇬🇧 Reino Unido' },
  { iata: 'MAN', name: 'Manchester',                region: '🇬🇧 Reino Unido' },
  { iata: 'EDI', name: 'Edimburgo',                 region: '🇬🇧 Reino Unido' },
  { iata: 'GLA', name: 'Glasgow',                   region: '🇬🇧 Reino Unido' },
  { iata: 'BHX', name: 'Birmingham',                region: '🇬🇧 Reino Unido' },
  { iata: 'DUB', name: 'Dublín',                    region: '🇬🇧 Reino Unido' },
  // Francia
  { iata: 'CDG', name: 'París Charles de Gaulle',   region: '🇫🇷 Francia' },
  { iata: 'ORY', name: 'París Orly',                region: '🇫🇷 Francia' },
  { iata: 'BVA', name: 'París Beauvais',            region: '🇫🇷 Francia' },
  { iata: 'NCE', name: 'Niza',                      region: '🇫🇷 Francia' },
  { iata: 'LYS', name: 'Lyon',                      region: '🇫🇷 Francia' },
  { iata: 'MRS', name: 'Marsella',                  region: '🇫🇷 Francia' },
  { iata: 'TLS', name: 'Toulouse',                  region: '🇫🇷 Francia' },
  { iata: 'BOD', name: 'Burdeos',                   region: '🇫🇷 Francia' },
  // Alemania
  { iata: 'FRA', name: 'Frankfurt',                 region: '🇩🇪 Alemania' },
  { iata: 'MUC', name: 'Múnich',                    region: '🇩🇪 Alemania' },
  { iata: 'BER', name: 'Berlín',                    region: '🇩🇪 Alemania' },
  { iata: 'HAM', name: 'Hamburgo',                  region: '🇩🇪 Alemania' },
  { iata: 'DUS', name: 'Düsseldorf',                region: '🇩🇪 Alemania' },
  { iata: 'STR', name: 'Stuttgart',                 region: '🇩🇪 Alemania' },
  { iata: 'CGN', name: 'Colonia',                   region: '🇩🇪 Alemania' },
  // Benelux
  { iata: 'AMS', name: 'Ámsterdam Schiphol',        region: '🇳🇱 Países Bajos' },
  { iata: 'BRU', name: 'Bruselas',                  region: '🇧🇪 Bélgica' },
  // Suiza / Austria
  { iata: 'ZRH', name: 'Zúrich',                    region: '🇨🇭 Suiza / Austria' },
  { iata: 'GVA', name: 'Ginebra',                   region: '🇨🇭 Suiza / Austria' },
  { iata: 'VIE', name: 'Viena',                     region: '🇨🇭 Suiza / Austria' },
  // Italia
  { iata: 'FCO', name: 'Roma Fiumicino',            region: '🇮🇹 Italia' },
  { iata: 'MXP', name: 'Milán Malpensa',            region: '🇮🇹 Italia' },
  { iata: 'LIN', name: 'Milán Linate',              region: '🇮🇹 Italia' },
  { iata: 'NAP', name: 'Nápoles',                   region: '🇮🇹 Italia' },
  { iata: 'VCE', name: 'Venecia',                   region: '🇮🇹 Italia' },
  { iata: 'BLQ', name: 'Bolonia',                   region: '🇮🇹 Italia' },
  { iata: 'CTA', name: 'Catania',                   region: '🇮🇹 Italia' },
  { iata: 'PMO', name: 'Palermo',                   region: '🇮🇹 Italia' },
  // Portugal
  { iata: 'LIS', name: 'Lisboa',                    region: '🇵🇹 Portugal' },
  { iata: 'OPO', name: 'Oporto',                    region: '🇵🇹 Portugal' },
  { iata: 'FAO', name: 'Faro',                      region: '🇵🇹 Portugal' },
  // Escandinavia
  { iata: 'CPH', name: 'Copenhague',                region: '🇸🇪 Escandinavia' },
  { iata: 'ARN', name: 'Estocolmo Arlanda',         region: '🇸🇪 Escandinavia' },
  { iata: 'OSL', name: 'Oslo',                      region: '🇸🇪 Escandinavia' },
  { iata: 'HEL', name: 'Helsinki',                  region: '🇸🇪 Escandinavia' },
  // Europa del Este
  { iata: 'WAW', name: 'Varsovia',                  region: '🌍 Europa del Este' },
  { iata: 'KRK', name: 'Cracovia',                  region: '🌍 Europa del Este' },
  { iata: 'BUD', name: 'Budapest',                  region: '🌍 Europa del Este' },
  { iata: 'PRG', name: 'Praga',                     region: '🌍 Europa del Este' },
  { iata: 'ATH', name: 'Atenas',                    region: '🌍 Europa del Este' },
  { iata: 'SKG', name: 'Tesalónica',                region: '🌍 Europa del Este' },
  { iata: 'SOF', name: 'Sofía',                     region: '🌍 Europa del Este' },
  { iata: 'OTP', name: 'Bucarest',                  region: '🌍 Europa del Este' },
  { iata: 'IST', name: 'Estambul',                  region: '🌍 Europa del Este' },
  { iata: 'SAW', name: 'Estambul Sabiha Gökçen',    region: '🌍 Europa del Este' },
  { iata: 'AYT', name: 'Antalya',                   region: '🌍 Europa del Este' },
  // África del Norte
  { iata: 'CMN', name: 'Casablanca',                region: '🌍 África del Norte' },
  { iata: 'RAK', name: 'Marrakech',                 region: '🌍 África del Norte' },
  { iata: 'TNG', name: 'Tánger',                    region: '🌍 África del Norte' },
  { iata: 'CAI', name: 'El Cairo',                  region: '🌍 África del Norte' },
  { iata: 'TUN', name: 'Túnez',                     region: '🌍 África del Norte' },
  // América
  { iata: 'JFK', name: 'Nueva York JFK',            region: '🌎 América' },
  { iata: 'EWR', name: 'Nueva York Newark',         region: '🌎 América' },
  { iata: 'MIA', name: 'Miami',                     region: '🌎 América' },
  { iata: 'ORD', name: 'Chicago',                   region: '🌎 América' },
  { iata: 'LAX', name: 'Los Ángeles',               region: '🌎 América' },
  { iata: 'BOS', name: 'Boston',                    region: '🌎 América' },
  { iata: 'ATL', name: 'Atlanta',                   region: '🌎 América' },
  { iata: 'DFW', name: 'Dallas',                    region: '🌎 América' },
  { iata: 'YYZ', name: 'Toronto',                   region: '🌎 América' },
  { iata: 'YUL', name: 'Montreal',                  region: '🌎 América' },
  { iata: 'MEX', name: 'Ciudad de México',          region: '🌎 América' },
  { iata: 'CUN', name: 'Cancún',                    region: '🌎 América' },
  { iata: 'BOG', name: 'Bogotá',                    region: '🌎 América' },
  { iata: 'LIM', name: 'Lima',                      region: '🌎 América' },
  { iata: 'EZE', name: 'Buenos Aires',              region: '🌎 América' },
  { iata: 'GRU', name: 'São Paulo',                 region: '🌎 América' },
  { iata: 'SCL', name: 'Santiago de Chile',         region: '🌎 América' },
  { iata: 'UIO', name: 'Quito',                     region: '🌎 América' },
  { iata: 'HAV', name: 'La Habana',                 region: '🌎 América' },
  { iata: 'SDQ', name: 'Santo Domingo',             region: '🌎 América' },
  { iata: 'PTY', name: 'Ciudad de Panamá',          region: '🌎 América' },
  { iata: 'MDE', name: 'Medellín',                  region: '🌎 América' },
  // Oriente Medio
  { iata: 'DXB', name: 'Dubái',                     region: '🌍 Oriente Medio' },
  { iata: 'DOH', name: 'Doha',                      region: '🌍 Oriente Medio' },
  { iata: 'AUH', name: 'Abu Dabi',                  region: '🌍 Oriente Medio' },
  { iata: 'RUH', name: 'Riad',                      region: '🌍 Oriente Medio' },
  { iata: 'TLV', name: 'Tel Aviv',                  region: '🌍 Oriente Medio' },
  { iata: 'AMM', name: 'Amán',                      region: '🌍 Oriente Medio' },
  // Asia
  { iata: 'BKK', name: 'Bangkok Suvarnabhumi',      region: '🌏 Asia' },
  { iata: 'HKG', name: 'Hong Kong',                 region: '🌏 Asia' },
  { iata: 'NRT', name: 'Tokio Narita',              region: '🌏 Asia' },
  { iata: 'HND', name: 'Tokio Haneda',              region: '🌏 Asia' },
  { iata: 'ICN', name: 'Seúl Incheon',              region: '🌏 Asia' },
  { iata: 'SIN', name: 'Singapur',                  region: '🌏 Asia' },
  { iata: 'KUL', name: 'Kuala Lumpur',              region: '🌏 Asia' },
  { iata: 'PEK', name: 'Pekín',                     region: '🌏 Asia' },
  { iata: 'PVG', name: 'Shanghái Pudong',           region: '🌏 Asia' },
  { iata: 'BOM', name: 'Mumbai',                    region: '🌏 Asia' },
  { iata: 'DEL', name: 'Nueva Delhi',               region: '🌏 Asia' },
  { iata: 'DPS', name: 'Bali',                      region: '🌏 Asia' },
  // Oceanía / África subsahariana
  { iata: 'SYD', name: 'Sídney',                    region: '🌏 Oceanía' },
  { iata: 'MEL', name: 'Melbourne',                 region: '🌏 Oceanía' },
  { iata: 'JNB', name: 'Johannesburgo',             region: '🌍 África' },
  { iata: 'CPT', name: 'Ciudad del Cabo',           region: '🌍 África' },
];

export const AIRPORT_GROUPS = AIRPORTS.reduce((acc, a) => {
  if (!acc[a.region]) acc[a.region] = [];
  acc[a.region].push(a);
  return acc;
}, {});
